{
  imports = [
    ./alejandra.nix
    ./audio.nix
    ./bluetooth.nix
    ./btop.nix
    ./dbus.nix
    ./direnv.nix
    ./firewall.nix
    ./geistmono.nix
    ./libnotify.nix
    ./restituo.nix
    ./sl.nix
    ./tailscale.nix
    ./tree.nix
    ./upower.nix
    ./wget.nix
    ./zip.nix
    ./zsh.nix
  ];
}
